const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function load(file,mocks={},cache={}){if(cache[file])return cache[file].exports;const module={exports:{}};cache[file]=module;const code=ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,Date,Intl,console,require(name){if(name in mocks)return mocks[name];if(name==='zod')return require('zod');if(name==='server-only')return {};if(name.startsWith('@/'))return load('src/'+name.slice(2)+'.ts',mocks,cache);if(name.startsWith('.'))return load(path.join(path.dirname(file),name)+'.ts',mocks,cache);throw Error(name)}});return module.exports;}
const parse=load('src/lib/pessoas/initial-import.ts').parseInitialImport;
const csv='nome_completo;cpf;funcao;data_admissao;salario_base\nPessoa Teste;52998224725;Analista;01/01/2026;1234,50';
test('initial base normalizes names, date and salary',()=>{const [r]=parse(csv);assert.equal(r.nome,'Pessoa');assert.equal(r.sobrenome,'Teste');assert.equal(r.data_admissao,'2026-01-01');assert.equal(r.salario_base,1234.5);assert.equal(r.ativo,true)});
test('rejects privileged columns, malformed salary, formulas, invalid and duplicate CPFs',()=>{
 for(const text of [csv.replace('salario_base','role_id'),csv.replace('1234,50','1.234,50'),csv.replace('Pessoa Teste','=SUM(1)'),csv.replace('52998224725','00000000000'),csv+'\n'+csv.split('\n')[1]])assert.throws(()=>parse(text));
});
test('rejects future/impossible dates, blank names and excess rows',()=>{
 for(const text of [csv.replace('01/01/2026','01/01/2999'),csv.replace('01/01/2026','30/02/2026'),csv.replace('Pessoa Teste',''),csv+'\n'+Array(200).fill(csv.split('\n')[1]).join('\n')])assert.throws(()=>parse(text));
});
function fixture(opts={}){const writes=[];const client={from(table){const q={select(){return q},eq(){return q},in(){return q},maybeSingle(){return q},insert(rows){writes.push(rows);return Promise.resolve({error:opts.race?{message:'unique violation'}:null})},then(resolve){return Promise.resolve(table==='units'?{data:opts.noUnit?null:{id:'11111111-1111-4111-8111-111111111111'},error:null}:{data:opts.duplicate?[{cpf:'52998224725'}]:[],error:opts.failure?{message:'offline'}:null}).then(resolve)}};return q}};const api=load('src/app/pessoas/importacao-inicial/actions.ts',{'@kph/auth/server':{requireRole:async roles=>{assert.equal(roles[0],'founder');if(opts.denied)throw Error('denied')}},'@kph/db/supabase/server':{createSupabaseServerClient:async()=>client},'next/cache':{revalidatePath(){}}});return {writes,run:commit=>api.initialImport({unitId:'11111111-1111-4111-8111-111111111111',text:csv},commit)}};
test('preview never writes and commit inserts one batch bound to selected unit',async()=>{const f=fixture();assert.equal((await f.run(false)).ok,true);assert.equal(f.writes.length,0);assert.equal((await f.run(true)).ok,true);assert.equal(f.writes.length,1);assert.equal(f.writes[0][0].unit_id,'11111111-1111-4111-8111-111111111111')});
test('missing unit, lookup failure, duplicate CPF and unauthorized user cannot write',async()=>{for(const options of [{noUnit:true},{failure:true},{duplicate:true}]){const f=fixture(options);assert.equal((await f.run(true)).ok,false);assert.equal(f.writes.length,0)}const f=fixture({denied:true});await assert.rejects(f.run(true));assert.equal(f.writes.length,0)});
test('concurrent duplicate insertion is reported as failure',async()=>{const f=fixture({race:true});assert.equal((await f.run(true)).ok,false)});
